fieldLayouts:
  77fbf346-53be-42f7-8f47-d88ac3cd219c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: cc7a7777-17c5-45ef-829d-9b277cb85134
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4fea65b6-ace0-410c-b9b0-006dfb431f65
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dfb201c1-5d86-40c2-8ef8-8a447a607828
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fe83906d-6f96-4f77-9151-41326628a78d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1abe3543-0a12-4298-ad7d-1a93ca2d280c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: contact
hasTitleField: false
name: Contact
section: 65923fc6-a652-4d40-88b1-c54766df929e
sortOrder: 1
titleFormat: '{section.name|raw}'
